# Generated by Django 5.0.6 on 2024-05-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_note_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
