# Generated by Django 5.0.6 on 2024-06-19 10:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_usedpasswordresettoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsedPasswordResetToken',
            new_name='UsedToken',
        ),
    ]
