# Generated by Django 5.0.6 on 2024-06-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_usedpasswordresettoken_usedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
